### ISSUE TITLE
Not able to change abilities & stiles in the sheet

### ISSUE THREAD

**Issue by AlexTCO** [Muttley/foundryvtt-dishonored#41]
All abilities and stiles are set to 4 by default, when I change one to other value, e.g. 2, it is reset to 4.
Also not possible to set stress to a higher/smaller value (4 by deafult and apparently not changeable).

Thank you.

**Comment by Muttley** [comment]
All Skills and Styles have a minimum of 4 and maximum of 8.  See the core rulebook pages 61 and 62.
